const card = document.createElement('article');
card.classList.add('game-card');
const cover = document.createElement('div');
const content = document.createElement('div');
cover.classList.add('game-card__cover');
content.classList.add('game-card__content');
card.append(cover);
card.append(content);
const img = document.createElement('img');
img.classList.add('game-card__image');
const rait_bage = document.createElement('span');
rait_bage.classList.add('game-card__rating-badge');
rait_bage.textContent = '9/10';
cover.append(img);
cover.append(rait_bage);
const title = document.createElement('h4');
title.classList.add('game-card__title');
title.textContent = 'Cyberpunk 2077';
const meta = document.createElement('div');
meta.classList.add('game-card__meta');
content.append(title);
content.append(meta);
const year = document.createElement('span');
year.classList.add('game-card__year');
year.textContent = '2020';
const genre = document.createElement('span');
genre.classList.add('game-card__genre');
genre.textContent = 'RPG';
meta.append(year);
meta.append(genre);
